# Generated by Django 5.2.5 on 2025-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='core.colaborador'),
        ),
    ]
