# Generated by Django 5.2.5 on 2025-08-25 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_proyecto_colaboradores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnticipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('masivo', 'Anticipo Masivo'), ('individual', 'Anticipo Individual')], default='individual', max_length=20)),
                ('concepto', models.CharField(default='Anticipo por proyecto', max_length=200)),
                ('fecha_anticipo', models.DateField(auto_now_add=True)),
                ('fecha_liquidacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('liquidado', 'Liquidado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos_proyecto', to='core.colaborador')),
                ('liquidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos_liquidados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos_proyecto', to='core.proyecto')),
            ],
            options={
                'ordering': ['-fecha_anticipo'],
                'unique_together': {('proyecto', 'colaborador', 'fecha_anticipo')},
            },
        ),
    ]
