# Generated by Django 5.2.5 on 2025-08-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_anticipoproyecto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anticipoproyecto',
            unique_together=set(),
        ),
    ]
