# Generated by Django 5.2.5 on 2025-08-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_anticipoproyecto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por unidad', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='stock_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stock mínimo recomendado', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Unidad de medida (m², m³, kg, etc.)', max_length=50, null=True),
        ),
    ]
