# Generated by Django 5.2.5 on 2025-08-28 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_iteminventario_precio_unitario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la carpeta', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la carpeta')),
                ('color', models.CharField(default='#667eea', help_text='Color de la carpeta (hex)', max_length=7)),
                ('icono', models.CharField(default='fas fa-folder', help_text='Clase del icono de FontAwesome', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('carpeta_padre', models.ForeignKey(blank=True, help_text='Carpeta padre (dejar vacío para carpeta raíz)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='core.carpetaproyecto')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Carpeta de Proyecto',
                'verbose_name_plural': 'Carpetas de Proyecto',
                'ordering': ['nombre'],
                'unique_together': {('proyecto', 'carpeta_padre', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='archivoproyecto',
            name='carpeta',
            field=models.ForeignKey(blank=True, help_text='Carpeta donde se almacena el archivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.carpetaproyecto'),
        ),
    ]
