# Generated by Django 5.2.5 on 2025-09-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carpetaproyecto_archivoproyecto_carpeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Constructora XYZ', max_length=200)),
                ('moneda', models.CharField(choices=[('GTQ', 'Quetzal (GTQ)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='GTQ', max_length=3)),
                ('zona_horaria', models.CharField(choices=[('America/Guatemala', 'Guatemala (GMT-6)'), ('America/New_York', 'Nueva York (GMT-5)'), ('Europe/Madrid', 'Madrid (GMT+1)')], default='America/Guatemala', max_length=50)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5)),
                ('max_usuarios_simultaneos', models.PositiveIntegerField(default=5)),
                ('tiempo_sesion', models.PositiveIntegerField(default=480, help_text='Tiempo en minutos')),
                ('respaldo_automatico', models.BooleanField(default=False)),
                ('notificaciones_email', models.BooleanField(default=False)),
                ('email_host', models.CharField(blank=True, max_length=200)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_username', models.CharField(blank=True, max_length=200)),
                ('email_password', models.CharField(blank=True, max_length=200)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
