# Generated by Django 5.2.5 on 2025-09-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriagasto',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color hexadecimal (ej: #007bff)', max_length=7),
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='icono',
            field=models.CharField(default='fas fa-tools', help_text='Clase de Font Awesome (ej: fas fa-tools)', max_length=50),
        ),
    ]
