# Generated by Django 5.2.5 on 2025-09-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_categoriagasto_color_categoriagasto_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='aplicado_al_proyecto',
            field=models.BooleanField(default=False, help_text='Indica si el anticipo se aplicó directamente al proyecto'),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='monto_aplicado_proyecto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto aplicado directamente al proyecto', max_digits=12),
        ),
    ]
