# Generated by Django 5.2.5 on 2025-09-09 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_anticipo_aplicado_al_proyecto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aplicar'), ('aplicado', 'Aplicado a Facturas'), ('liquidado', 'Liquidado'), ('devuelto', 'Devuelto al Cliente'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('tipo', models.CharField(choices=[('proyecto', 'Proyecto'), ('factura', 'Factura'), ('reunion', 'Reunión'), ('entrega', 'Entrega'), ('vencimiento', 'Vencimiento'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Evento')),
                ('color', models.CharField(choices=[('#667eea', 'Azul'), ('#28a745', 'Verde'), ('#dc3545', 'Rojo'), ('#ffc107', 'Amarillo'), ('#17a2b8', 'Cian'), ('#6f42c1', 'Púrpura'), ('#fd7e14', 'Naranja'), ('#20c997', 'Turquesa')], default='#667eea', max_length=7, verbose_name='Color')),
                ('todo_el_dia', models.BooleanField(default=True, verbose_name='Todo el día')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.factura', verbose_name='Factura relacionada')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proyecto', verbose_name='Proyecto relacionado')),
            ],
            options={
                'verbose_name': 'Evento del Calendario',
                'verbose_name_plural': 'Eventos del Calendario',
                'ordering': ['fecha_inicio', 'hora_inicio'],
            },
        ),
    ]
