# Generated by Django 4.2.7 on 2025-09-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_anticipo_estado_eventocalendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='modulos_activos',
            field=models.ManyToManyField(blank=True, related_name='roles_activos', to='core.modulo'),
        ),
    ]
