# Generated by Django 4.2.7 on 2025-09-21 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_rol_modulos_activos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadorDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del trabajador')),
                ('pago_diario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago diario (Q)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores_diarios', to='core.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Trabajador Diario',
                'verbose_name_plural': 'Trabajadores Diarios',
                'ordering': ['nombre'],
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RegistroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin del período')),
                ('dias_trabajados', models.IntegerField(verbose_name='Días trabajados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_trabajo', to='core.trabajadordiario', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Registro de Trabajo',
                'verbose_name_plural': 'Registros de Trabajo',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
