# Generated by Django 4.2.7 on 2025-09-25 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_trabajadordiario_registrotrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotrabajo',
            name='dias_trabajados',
            field=models.IntegerField(help_text='Número de días trabajados en este período', verbose_name='Días trabajados'),
        ),
        migrations.CreateModel(
            name='AnticipoTrabajadorDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del anticipo')),
                ('fecha_anticipo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del anticipo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicado', 'Aplicado'), ('liquidado', 'Liquidado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='core.trabajadordiario', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Anticipo de Trabajador Diario',
                'verbose_name_plural': 'Anticipos de Trabajadores Diarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
