# Generated by Django 4.2.7 on 2025-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_registrotrabajo_dias_trabajados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoproyecto',
            name='tipo',
            field=models.CharField(choices=[('plano', 'Plano'), ('documento', 'Documento'), ('imagen', 'Imagen'), ('excel', 'Excel'), ('contrato', 'Contrato'), ('permiso', 'Permiso'), ('otro', 'Otro')], default='documento', max_length=20),
        ),
    ]
