# Generated by Django 4.2.7 on 2025-09-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_archivoproyecto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha límite para el pago (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre el gasto'),
        ),
    ]
