# Generated by Django 4.2.7 on 2025-09-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_gasto_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
