# Generated by Django 4.2.7 on 2025-09-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_gasto_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.FloatField(),
        ),
    ]
