# Generated by Django 4.2.7 on 2025-10-01 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_alter_gasto_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaLiquidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de liquidación')),
                ('total_salarios', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Salarios')),
                ('total_anticipos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Anticipos Liquidados')),
                ('total_planilla', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de la Planilla')),
                ('cantidad_personal', models.IntegerField(default=0, verbose_name='Cantidad de Personal')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('liquidada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Liquidada por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas_liquidadas', to='core.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Planilla Liquidada',
                'verbose_name_plural': 'Planillas Liquidadas',
                'ordering': ['-fecha_liquidacion'],
            },
        ),
    ]
