# Generated by Django 4.2.7 on 2025-10-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_planillaliquidada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipoproyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('liquidado', 'Liquidado'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
