# Generated by Django 4.2.7 on 2025-10-01 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_trabajadordiario_planilla'),
    ]

    operations = []
