# Generated by Django 4.2.7 on 2025-10-01 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_alter_anticipoproyecto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaTrabajadoresDiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Planilla Semana 1, Planilla Enero 2025', max_length=200, verbose_name='Nombre de la planilla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin del período')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('archivada', 'Archivada')], default='activa', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('finalizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Finalizada por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas_trabajadores_diarios', to='core.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Planilla de Trabajadores Diarios',
                'verbose_name_plural': 'Planillas de Trabajadores Diarios',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='trabajadordiario',
            name='planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='core.planillatrabajadoresdiarios', verbose_name='Planilla'),
        ),
    ]
