# Generated by Django 4.2.7 on 2025-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_planillatrabajadoresdiarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillatrabajadoresdiarios',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin del período'),
        ),
        migrations.AlterField(
            model_name='planillatrabajadoresdiarios',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del período'),
        ),
    ]
