# Generated by Django 4.2.7 on 2025-10-02 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_planillatrabajadoresdiarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadordiario',
            name='planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='core.planillatrabajadoresdiarios', verbose_name='Planilla'),
        ),
    ]
