# Generated by Django 4.2.7 on 2025-10-02 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_trabajadordiario_planilla'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trabajadordiario',
            unique_together={('planilla', 'nombre')},
        ),
    ]
