# Generated by Django 4.2.7 on 2025-10-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_planillatrabajadoresdiarios_fecha_fin_and_more'),
        ('core', '0026_cambiar_unique_trabajador_diario'),
    ]

    operations = [
    ]
