# Generated by Django 4.2.7 on 2025-10-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20251003_0937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='variacionpresupuesto',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='variacionpresupuesto',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='variacionpresupuesto',
            name='presupuesto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='presupuesto',
        ),
        migrations.DeleteModel(
            name='PartidaPresupuesto',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='VariacionPresupuesto',
        ),
    ]
