# Generated by Django 4.2.7 on 2025-10-08 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_eliminar_presupuesto_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('factura_completa', 'Factura Completa'), ('factura_parcial', 'Factura Parcial'), ('anticipo', 'Anticipo'), ('pago_directo', 'Pago Directo'), ('otros', 'Otros')], default='factura_completa', max_length=20)),
                ('numero_documento', models.CharField(help_text='Número de factura o documento de referencia', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción del ingreso')),
                ('monto_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal del ingreso', max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, help_text='IVA del ingreso', max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total del ingreso', max_digits=12)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión del documento')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now, help_text='Fecha de registro del ingreso')),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha de pago (si aplica)', null=True)),
                ('pagado', models.BooleanField(default=False, help_text='Indica si el ingreso ha sido pagado')),
                ('porcentaje_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del monto que ha sido pagado', max_digits=5)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_creados', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_proyecto', to='core.factura')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_modificados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Ingreso por Proyecto',
                'verbose_name_plural': 'Ingresos por Proyecto',
                'ordering': ['-fecha_emision', '-fecha_registro'],
                'indexes': [models.Index(fields=['proyecto', 'fecha_emision'], name='core_ingres_proyect_1c47c3_idx'), models.Index(fields=['factura'], name='core_ingres_factura_e100f5_idx'), models.Index(fields=['pagado', 'fecha_pago'], name='core_ingres_pagado_da5689_idx')],
            },
        ),
    ]
