# Generated by Django 4.2.7 on 2025-10-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_agregar_ingreso_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='fecha_vencimiento',
        ),
        migrations.AlterField(
            model_name='ingresoproyecto',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA del ingreso (en dólares)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingresoproyecto',
            name='monto_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal del ingreso (en dólares)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingresoproyecto',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, help_text='Monto total del ingreso (en dólares)', max_digits=12),
        ),
    ]
