# Generated by Django 4.2.7 on 2025-10-18 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_remove_fecha_vencimiento_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(help_text='Número único de la cotización', max_length=50, unique=True)),
                ('titulo', models.CharField(help_text='Título descriptivo de la cotización', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de los servicios')),
                ('tipo_cotizacion', models.CharField(choices=[('inicial', 'Cotización Inicial'), ('adicional', 'Cotización Adicional'), ('cambio_alcance', 'Cambio de Alcance'), ('servicios_extra', 'Servicios Extra'), ('mantenimiento', 'Mantenimiento'), ('otros', 'Otros')], default='inicial', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('monto_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal de la cotización (en dólares)', max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, help_text='ITBMS de la cotización (en dólares)', max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la cotización (en dólares)', max_digits=12)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la cotización')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite de validez de la cotización')),
                ('fecha_aceptacion', models.DateField(blank=True, help_text='Fecha de aceptación por el cliente', null=True)),
                ('validez_dias', models.PositiveIntegerField(default=30, help_text='Días de validez de la cotización')),
                ('condiciones_pago', models.TextField(blank=True, help_text='Condiciones de pago')),
                ('terminos_condiciones', models.TextField(blank=True, help_text='Términos y condiciones generales')),
                ('archivo_cotizacion', models.FileField(blank=True, help_text='Archivo PDF de la cotización', null=True, upload_to='cotizaciones/')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones internas')),
                ('notas_cliente', models.TextField(blank=True, help_text='Notas o comentarios del cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision', '-numero_cotizacion'],
                'indexes': [models.Index(fields=['proyecto', 'estado'], name='core_cotiza_proyect_3ff007_idx'), models.Index(fields=['cliente', 'estado'], name='core_cotiza_cliente_4ee77a_idx'), models.Index(fields=['fecha_emision'], name='core_cotiza_fecha_e_b5366c_idx'), models.Index(fields=['fecha_vencimiento'], name='core_cotiza_fecha_v_ff83fb_idx')],
            },
        ),
    ]
