# Generated by Django 4.2.7 on 2025-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='porcentaje_itbms',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Porcentaje de ITBMS aplicado', max_digits=5),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto del ITBMS', max_digits=12),
        ),
    ]
