# Generated by Django 4.2.7 on 2025-10-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_factura_porcentaje_itbms_alter_factura_monto_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del item', max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad del item', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario de venta', max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, help_text='Precio de costo del item', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del item (cantidad × precio unitario)', max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización del item')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cotizacion')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['cotizacion', 'orden'], name='core_itemco_cotizac_6feff4_idx')],
            },
        ),
    ]
