# Generated by Django 4.2.7 on 2025-10-31 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_itemcotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReutilizable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del item', max_length=500, unique=True)),
                ('categoria', models.CharField(blank=True, help_text='Categoría del item para organizarlos', max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario de venta', max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, help_text='Precio de costo del item', max_digits=12)),
                ('activo', models.BooleanField(default=True, help_text='Si el item está activo y disponible')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el item')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_reutilizables_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_reutilizables_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Reutilizable',
                'verbose_name_plural': 'Items Reutilizables',
                'ordering': ['categoria', 'descripcion'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='core_itemre_categor_c5183e_idx')],
            },
        ),
    ]
