# Generated by Django 4.2.7 on 2025-10-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_itemreutilizable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha límite de validez de la cotización', null=True),
        ),
    ]
