# Generated by Django 4.2.7 on 2025-10-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_cotizacion_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planillatrabajadoresdiarios',
            options={'ordering': ['-año', '-mes', '-fecha_creacion'], 'verbose_name': 'Planilla de Trabajadores Diarios', 'verbose_name_plural': 'Planillas de Trabajadores Diarios'},
        ),
        migrations.AlterUniqueTogether(
            name='planillatrabajadoresdiarios',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planillatrabajadoresdiarios',
            name='año',
            field=models.IntegerField(blank=True, help_text='Ej: 2025', null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='planillatrabajadoresdiarios',
            name='mes',
            field=models.IntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True, verbose_name='Mes'),
        ),
        migrations.AlterUniqueTogether(
            name='planillatrabajadoresdiarios',
            unique_together={('proyecto', 'mes', 'año')},
        ),
    ]
