# Generated by Django 4.2.7 on 2025-10-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_planilla_mes_año'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planillaliquidada',
            options={'ordering': ['-año', '-mes', '-fecha_liquidacion'], 'verbose_name': 'Planilla Liquidada', 'verbose_name_plural': 'Planillas Liquidadas'},
        ),
        migrations.AddField(
            model_name='planillaliquidada',
            name='año',
            field=models.IntegerField(default=2025, help_text='Ej: 2025', verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='planillaliquidada',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1, verbose_name='Mes'),
        ),
        migrations.AlterUniqueTogether(
            name='planillaliquidada',
            unique_together={('proyecto', 'mes', 'año')},
        ),
    ]
