# Generated by Django 4.2.7 on 2025-10-31 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_planilla_liquidada_mes_año'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planillatrabajadoresdiarios',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Planilla de Trabajadores Diarios', 'verbose_name_plural': 'Planillas de Trabajadores Diarios'},
        ),
        migrations.AlterUniqueTogether(
            name='planillatrabajadoresdiarios',
            unique_together={('proyecto', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='planillatrabajadoresdiarios',
            name='año',
        ),
        migrations.RemoveField(
            model_name='planillatrabajadoresdiarios',
            name='mes',
        ),
    ]
