# Generated by Django 4.2.7 on 2025-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_revertir_trabajadores_diarios_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planillaliquidada',
            options={'ordering': ['-año', '-mes', '-quincena', '-fecha_liquidacion'], 'verbose_name': 'Planilla Liquidada', 'verbose_name_plural': 'Planillas Liquidadas'},
        ),
        migrations.AlterUniqueTogether(
            name='planillaliquidada',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planillaliquidada',
            name='quincena',
            field=models.IntegerField(blank=True, choices=[(1, 'Primera Quincena (1-15)'), (2, 'Segunda Quincena (16-fin)')], help_text='Solo para períodos quincenales', null=True, verbose_name='Quincena'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='periodo_pago',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal')], default='mensual', max_length=20, verbose_name='Período de Pago'),
        ),
        migrations.AlterUniqueTogether(
            name='planillaliquidada',
            unique_together={('proyecto', 'mes', 'año', 'quincena')},
        ),
    ]
