# Generated by Django 4.2.7 on 2025-10-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_proyecto_periodo_pago_y_quincena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='periodo_pago',
        ),
    ]
