# Generated by Django 4.2.7 on 2025-10-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_eliminar_periodo_pago_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillaliquidada',
            name='quincena',
            field=models.IntegerField(choices=[(1, 'Primera Quincena (1-15)'), (2, 'Segunda Quincena (16-fin)')], default=1, help_text='Quincena del pago', verbose_name='Quincena'),
        ),
    ]
