# Generated by Django 4.2.7 on 2025-11-01 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_quincena_obligatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencion_seguro_social', models.DecimalField(decimal_places=2, default=9.75, help_text='Porcentaje de retención del seguro social', max_digits=5, verbose_name='Seguro Social (%)')),
                ('retencion_educativo', models.DecimalField(decimal_places=2, default=1.25, help_text='Porcentaje de retención del seguro educativo', max_digits=5, verbose_name='Seguro Educativo (%)')),
                ('retencion_impuesto_renta', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de ISR (varía según salario)', max_digits=5, verbose_name='Impuesto sobre la Renta (%)')),
                ('bono_alimentacion', models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo mensual', max_digits=10, verbose_name='Bono de Alimentación')),
                ('bono_transporte', models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo mensual', max_digits=10, verbose_name='Bono de Transporte')),
                ('bono_produccion', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje sobre el salario', max_digits=5, verbose_name='Bono de Producción (%)')),
                ('aplicar_retenciones', models.BooleanField(default=True, verbose_name='Aplicar Retenciones')),
                ('aplicar_bonos', models.BooleanField(default=True, verbose_name='Aplicar Bonos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_planilla', to='core.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Configuración de Planilla',
                'verbose_name_plural': 'Configuraciones de Planilla',
            },
        ),
    ]
