# Generated by Django 4.2.7 on 2025-11-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_configuracion_planilla_retenciones_bonos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionplanilla',
            name='retencion_impuesto_renta',
        ),
    ]
