# Generated by Django 4.2.7 on 2025-11-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_eliminar_isr_configuracion_planilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionplanilla',
            name='bono_alimentacion',
        ),
        migrations.RemoveField(
            model_name='configuracionplanilla',
            name='bono_transporte',
        ),
        migrations.AddField(
            model_name='configuracionplanilla',
            name='bono_general',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo mensual', max_digits=10, verbose_name='Bono General'),
        ),
    ]
