# Generated by Django 4.2.7 on 2025-11-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_simplificar_bonos_planilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionplanilla',
            name='retencion_educativo',
        ),
        migrations.AddField(
            model_name='configuracionplanilla',
            name='retencion_seguro_educativo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo mensual de retención del seguro educativo', max_digits=10, verbose_name='Seguro Educativo ($)'),
        ),
        migrations.AlterField(
            model_name='configuracionplanilla',
            name='retencion_seguro_social',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo mensual de retención del seguro social', max_digits=10, verbose_name='Seguro Social ($)'),
        ),
    ]
