# Generated by Django 4.2.7 on 2025-11-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_retenciones_monto_fijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='aplica_bono_general',
            field=models.BooleanField(default=True, help_text='Si este colaborador recibe el bono general', verbose_name='Aplica Bono General'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='aplica_bono_produccion',
            field=models.BooleanField(default=True, help_text='Si este colaborador recibe bono de producción', verbose_name='Aplica Bono de Producción'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='aplica_retenciones',
            field=models.BooleanField(default=True, help_text='Si este colaborador tiene retenciones de ley', verbose_name='Aplica Retenciones'),
        ),
    ]
