# Generated by Django 4.2.7 on 2025-11-01 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0046_colaborador_bonos_retenciones_individuales'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPostit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido de la nota')),
                ('color', models.CharField(default='#fef3c7', max_length=7, verbose_name='Color del post-it')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_postit', to='core.eventocalendario', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Nota Post-it',
                'verbose_name_plural': 'Notas Post-it',
                'ordering': ['creado_en'],
            },
        ),
    ]
