# Generated by Django 4.2.7 on 2025-11-01 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_notapostit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaMenuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Número de folio único', max_length=50, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_menuda_creados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_menuda', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Caja Menuda',
                'verbose_name_plural': 'Caja Menuda',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['fecha', 'activo'], name='core_cajame_fecha_db3954_idx'), models.Index(fields=['folio'], name='core_cajame_folio_f3230d_idx')],
            },
        ),
    ]
