# Generated by Django 4.2.7 on 2025-11-20 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0048_cajamenuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioTorrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción del servicio solicitado')),
                ('cantidad_torreros', models.PositiveIntegerField(default=1, help_text='Cantidad de torreros requeridos')),
                ('periodo', models.CharField(choices=[('dias', 'Por Días'), ('semanas', 'Por Semanas'), ('meses', 'Por Meses')], default='dias', max_length=20)),
                ('dias_solicitados', models.PositiveIntegerField(help_text='Total de días solicitados por el cliente')),
                ('dias_trabajados', models.PositiveIntegerField(default=0, help_text='Días efectivamente trabajados')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del servicio')),
                ('fecha_fin_estimada', models.DateField(help_text='Fecha estimada de finalización')),
                ('fecha_fin_real', models.DateField(blank=True, help_text='Fecha real de finalización', null=True)),
                ('tarifa_por_dia', models.DecimalField(decimal_places=2, help_text='Tarifa por día por torrero', max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total del servicio', max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Monto total pagado hasta el momento', max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pausado', 'Pausado')], default='activo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del servicio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_torreros', to='core.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_torreros_creados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, help_text='Proyecto asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Servicio de Torrero',
                'verbose_name_plural': 'Servicios de Torreros',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiasTrabajados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(help_text='Fecha en que se trabajaron los días')),
                ('dias_trabajados', models.PositiveIntegerField(help_text='Cantidad de días trabajados en esta fecha')),
                ('torreros_presentes', models.PositiveIntegerField(help_text='Cantidad de torreros que trabajaron')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del trabajo realizado')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('es_dia_extra', models.BooleanField(default=False, help_text='Marca si este registro excede los días solicitados')),
                ('aprobado', models.BooleanField(default=False, help_text='Indica si el registro ha sido aprobado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_dias_aprobados', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_dias_creados', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_dias', to='core.serviciotorrero')),
            ],
            options={
                'verbose_name': 'Registro de Días Trabajados',
                'verbose_name_plural': 'Registros de Días Trabajados',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PagoServicioTorrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('deposito', 'Depósito')], default='efectivo', max_length=20)),
                ('numero_referencia', models.CharField(blank=True, help_text='Número de referencia, cheque o transacción', max_length=100)),
                ('comprobante', models.FileField(blank=True, help_text='Comprobante de pago (opcional)', upload_to='comprobantes_torreros/')),
                ('concepto', models.CharField(help_text='Concepto del pago', max_length=200)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_torreros_registrados', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.serviciotorrero')),
            ],
            options={
                'verbose_name': 'Pago de Servicio de Torrero',
                'verbose_name_plural': 'Pagos de Servicios de Torreros',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddIndex(
            model_name='serviciotorrero',
            index=models.Index(fields=['cliente', 'estado'], name='core_servic_cliente_e7d958_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciotorrero',
            index=models.Index(fields=['fecha_inicio', 'estado'], name='core_servic_fecha_i_04a368_idx'),
        ),
        migrations.AddIndex(
            model_name='registrodiastrabajados',
            index=models.Index(fields=['servicio', 'fecha_registro'], name='core_regist_servici_76fc95_idx'),
        ),
        migrations.AddIndex(
            model_name='registrodiastrabajados',
            index=models.Index(fields=['aprobado'], name='core_regist_aprobad_755394_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoserviciotorrero',
            index=models.Index(fields=['servicio', 'fecha_pago'], name='core_pagose_servici_b4086a_idx'),
        ),
    ]
