# Generated by Django 4.2.7 on 2025-11-20 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0049_serviciotorrero_registrodiastrabajados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del torrero', max_length=200)),
                ('cedula', models.CharField(help_text='Cédula o documento de identidad', max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254)),
                ('direccion', models.TextField(blank=True, help_text='Dirección de residencia')),
                ('fecha_ingreso', models.DateField(help_text='Fecha de ingreso')),
                ('especialidad', models.CharField(blank=True, help_text='Especialidad o habilidad principal', max_length=100)),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, help_text='Tarifa diaria estándar', max_digits=10)),
                ('foto', models.ImageField(blank=True, help_text='Foto del torrero', upload_to='torreros/fotos/')),
                ('activo', models.BooleanField(default=True, help_text='Torrero activo en el sistema')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torreros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Torrero',
                'verbose_name_plural': 'Torreros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTorrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('tarifa_acordada', models.DecimalField(decimal_places=2, help_text='Tarifa acordada para este servicio', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.serviciotorrero')),
                ('torrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_torrero', to='core.torrero')),
            ],
            options={
                'verbose_name': 'Asignación de Torrero',
                'verbose_name_plural': 'Asignaciones de Torreros',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddIndex(
            model_name='torrero',
            index=models.Index(fields=['cedula'], name='core_torrer_cedula_d8f8af_idx'),
        ),
        migrations.AddIndex(
            model_name='torrero',
            index=models.Index(fields=['activo', 'nombre'], name='core_torrer_activo_ebf857_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignaciontorrero',
            unique_together={('servicio', 'torrero')},
        ),
    ]
