# Generated by Django 4.2.7 on 2025-11-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_torrero_asignaciontorrero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiastrabajados',
            name='dias_trabajados',
            field=models.DecimalField(decimal_places=1, help_text='Cantidad de días trabajados en esta fecha (puede ser 0.5, 1, 1.5, etc.)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrodiastrabajados',
            name='torreros_presentes',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de torreros que trabajaron'),
        ),
        migrations.AlterField(
            model_name='serviciotorrero',
            name='dias_solicitados',
            field=models.DecimalField(decimal_places=1, help_text='Total de días solicitados por el cliente', max_digits=6),
        ),
        migrations.AlterField(
            model_name='serviciotorrero',
            name='dias_trabajados',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Días efectivamente trabajados', max_digits=6),
        ),
    ]
