# Generated by Django 4.2.7 on 2025-11-21 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0051_alter_registrodiastrabajados_dias_trabajados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del subproyecto', max_length=200)),
                ('codigo', models.CharField(help_text='Código único del subproyecto (ej: PROJ-001-SUB-001)', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del subproyecto')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del subproyecto')),
                ('fecha_fin_estimada', models.DateField(help_text='Fecha estimada de finalización')),
                ('fecha_fin_real', models.DateField(blank=True, help_text='Fecha real de finalización', null=True)),
                ('monto_cotizado', models.DecimalField(decimal_places=2, default=0, help_text='Monto de la cotización asociada', max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de avance del subproyecto', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(blank=True, help_text='Cotización asociada a este subproyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproyectos', to='core.cotizacion')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(help_text='Proyecto principal al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='subproyectos', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Subproyecto',
                'verbose_name_plural': 'Subproyectos',
                'ordering': ['proyecto', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='subproyecto',
            field=models.ForeignKey(blank=True, help_text='Subproyecto asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='core.subproyecto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='subproyecto',
            field=models.ForeignKey(blank=True, help_text='Subproyecto asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='core.subproyecto'),
        ),
        migrations.AddIndex(
            model_name='subproyecto',
            index=models.Index(fields=['proyecto', 'estado'], name='core_subpro_proyect_0e4fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='subproyecto',
            index=models.Index(fields=['cotizacion'], name='core_subpro_cotizac_d86acb_idx'),
        ),
    ]
