# Generated by Django 4.2.7 on 2025-11-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_subproyecto_factura_subproyecto_gasto_subproyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproyecto',
            name='monto_cotizado',
        ),
        migrations.AlterField(
            model_name='configuracionplanilla',
            name='bono_produccion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo mensual', max_digits=10, verbose_name='Bono de Producción ($)'),
        ),
        migrations.AlterField(
            model_name='trabajadordiario',
            name='pago_diario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago diario ($)'),
        ),
    ]
