# Generated by Django 4.2.7 on 2025-11-29 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0053_cambiar_bono_produccion_a_monto_fijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20, verbose_name='Prioridad')),
                ('ubicacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ubicación/Dirección')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='planificaciones_bitacora', to='core.colaborador', verbose_name='Trabajadores en Planilla')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_bitacora', to='core.proyecto')),
                ('trabajadores_diarios', models.ManyToManyField(blank=True, related_name='planificaciones_bitacora', to='core.trabajadordiario', verbose_name='Trabajadores Diarios')),
            ],
            options={
                'verbose_name': 'Planificación de Bitácora',
                'verbose_name_plural': 'Planificaciones de Bitácora',
                'ordering': ['-fecha_inicio', '-creado_en'],
                'indexes': [models.Index(fields=['proyecto', 'estado'], name='core_planif_proyect_8577ab_idx'), models.Index(fields=['fecha_inicio', 'estado'], name='core_planif_fecha_i_d75d06_idx')],
            },
        ),
    ]
