# Generated by Django 4.2.7 on 2025-12-08 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0054_planificacion_bitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='bono_produccion_individual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monto fijo mensual individual para este colaborador. Si está en 0, se usa el bono general del proyecto.', max_digits=10, null=True, verbose_name='Bono de Producción Individual ($)'),
        ),
        migrations.CreateModel(
            name='AvancePlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_avance', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Avance')),
                ('descripcion', models.TextField(verbose_name='Descripción del Avance')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='avances_planificacion', to='core.colaborador', verbose_name='Colaboradores')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='core.planificacionbitacora', verbose_name='Planificación')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('trabajadores_diarios', models.ManyToManyField(blank=True, related_name='avances_planificacion', to='core.trabajadordiario', verbose_name='Trabajadores Diarios')),
            ],
            options={
                'verbose_name': 'Avance de Planificación',
                'verbose_name_plural': 'Avances de Planificaciones',
                'ordering': ['-fecha_avance', '-creado_en'],
                'indexes': [models.Index(fields=['planificacion', 'fecha_avance'], name='core_avance_planifi_5cd541_idx')],
            },
        ),
    ]
