# Generated by Django 4.2.7 on 2025-12-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_agregar_bono_produccion_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de la factura', upload_to='comprobantes_facturas/'),
        ),
    ]
