# Generated by Django 4.2.7 on 2025-12-27 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_comprobante_to_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoColaboradorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bono_individual', models.DecimalField(decimal_places=2, default=0, help_text='Bono individual mensual para este colaborador en este proyecto', max_digits=10, verbose_name='Bono Individual ($)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_proyectos', to='core.colaborador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_colaboradores', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Bono Individual de Colaborador',
                'verbose_name_plural': 'Bonos Individuales de Colaboradores',
                'unique_together': {('proyecto', 'colaborador')},
            },
        ),
    ]
