# Generated by Django 4.2.7 on 2025-12-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_add_bono_colaborador_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonocolaboradorproyecto',
            options={'verbose_name': 'Bono de Colaborador', 'verbose_name_plural': 'Bonos de Colaboradores'},
        ),
        migrations.AlterField(
            model_name='bonocolaboradorproyecto',
            name='bono_individual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bono mensual para este colaborador en este proyecto', max_digits=10, verbose_name='Bono ($)'),
        ),
    ]
