# Generated by Django 5.2.11 on 2026-03-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_bancos'),
        ('core', '0063_gasto_administrativo_prorrateo'),
    ]

    operations = [
    ]
