# Generated by Django 5.2.11 on 2026-03-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_merge_0063_bancos_0063_gasto_administrativo_prorrateo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bitacorasubtarea',
            new_name='core_bitaco_tarea_i_99fed1_idx',
            old_name='core_bitac_tarea_0c9a6a_idx',
        ),
        migrations.RenameIndex(
            model_name='bitacoratarea',
            new_name='core_bitaco_planifi_55d243_idx',
            old_name='core_bitac_planifi_9d76f3_idx',
        ),
        migrations.AlterField(
            model_name='bancocuenta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bitacorasubtarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bitacoratarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimientobanco',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
